"use client";
import { useEffect, useMemo, useRef, useState } from "react";

type Repo={name:string;html_url:string;description:string|null;language:string|null;stargazers_count:number};
const site={"title": "Project Constellation", "kind": "Explore", "description": "Explore how Harman’s projects connect across agents, quant, security, and automation.", "tabs": ["All", "AI Agents", "Quant Research", "Cybersecurity", "Automation"], "items": ["AI Agents", "Quant Research", "Cybersecurity", "Automation"]};
const facts=["Evidence before claims","Responsive by default","Motion with purpose","Human review for risk"];

export default function Home() {
 const [active,setActive]=useState(site.tabs[0]); const [selected,setSelected]=useState<string|null>(null); const [repos,setRepos]=useState<Repo[]>([]); const [reduced,setReduced]=useState(false);
 const modalRef=useRef<HTMLElement>(null); const triggerRef=useRef<HTMLButtonElement|null>(null);
 useEffect(()=>{const controller=new AbortController(); fetch("/api/github",{signal:controller.signal}).then(r=>r.ok?r.json():[]).then(x=>setRepos(Array.isArray(x)?x:[])).catch(error=>{if(error instanceof DOMException&&error.name==="AbortError")return; setRepos([])}); return()=>controller.abort()},[]);
 useEffect(()=>{if(!selected)return; const modal=modalRef.current; if(!modal)return; const previousOverflow=document.body.style.overflow; document.body.style.overflow="hidden"; const focusable=()=>Array.from(modal.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],[tabindex]:not([tabindex="-1"])')); focusable()[0]?.focus(); const onKeyDown=(event:KeyboardEvent)=>{if(event.key==="Escape"){setSelected(null);return} if(event.key!=="Tab")return; const nodes=focusable(); if(!nodes.length)return; const first=nodes[0],last=nodes[nodes.length-1]; if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}; document.addEventListener("keydown",onKeyDown); return()=>{document.removeEventListener("keydown",onKeyDown);document.body.style.overflow=previousOverflow;triggerRef.current?.focus()}},[selected]);
 const filtered=useMemo(()=>site.items.filter((x:string)=>active===site.tabs[0]||x.toLowerCase().includes(active.toLowerCase())),[active]);
 const openModule=(item:string,event:React.MouseEvent<HTMLButtonElement>)=>{triggerRef.current=event.currentTarget;setSelected(item)};
 return <main className={reduced?"reduced":undefined}>
  <header className="top"><a className="brand" href="#top">HARMAN<span>.</span></a><nav aria-label="Project filters">{site.tabs.map((tab:string)=><button className={active===tab?"active":""} aria-pressed={active===tab} onClick={()=>setActive(tab)} key={tab}>{tab}</button>)}</nav><button className="motion" aria-pressed={reduced} onClick={()=>setReduced(!reduced)}>{reduced?"Motion off":"Motion on"}</button></header>
  <section className="hero" id="top"><div className="eyebrow">{site.kind} / HARMAN HANJRA</div><h1>{site.title}</h1><p>{site.description}</p><div className="hero-actions"><a className="primary" href="#workspace">Enter workspace ↓</a><a className="secondary" href="https://github.com/harmanhanjra" target="_blank" rel="noreferrer">GitHub ↗</a></div></section>
  <section className="workspace" id="workspace"><div className="section-line"><span>LIVE WORKSPACE</span><span>{filtered.length} ACTIVE MODULES</span></div><div className="module-grid">{filtered.map((item:string,i:number)=><button className={`module module-${(i%4)+1}`} aria-haspopup="dialog" key={item} onClick={event=>openModule(item,event)}><small>0{i+1}</small><strong>{item}</strong><span>Inspect module ↗</span></button>)}</div></section>
  <section className="evidence"><div><div className="eyebrow">SYSTEM PRINCIPLES</div><h2>Useful intelligence, documented.</h2></div><div className="fact-list">{facts.map(f=><div className="fact" key={f}><span>+</span>{f}</div>)}</div></section>
  <section className="github" id="github"><div className="section-line"><span>OPEN SOURCE SIGNAL</span><a href="https://github.com/harmanhanjra" target="_blank" rel="noreferrer">View GitHub ↗</a></div><div className="repo-grid">{repos.length?repos.map(repo=><a className="repo" href={repo.html_url} target="_blank" rel="noreferrer" key={repo.name}><strong>{repo.name.replaceAll("-"," ")}</strong><p>{repo.description||"Harman Hanjra project repository."}</p><small>{repo.language||"Open source"} · ★ {repo.stargazers_count}</small></a>):<div className="empty">GitHub repositories are temporarily unavailable.</div>}</div></section>
  <footer><span>© 2026 HARMAN HANJRA</span><span>{site.title} / BUILT WITH NEXT.JS</span></footer>
  {selected&&<div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setSelected(null)}}><section ref={modalRef} className="modal" role="dialog" aria-modal="true" aria-labelledby="module-title" aria-describedby="module-description"><button className="close" onClick={()=>setSelected(null)} aria-label="Close module inspector">×</button><div className="eyebrow">MODULE INSPECTOR</div><h2 id="module-title">{selected}</h2><p id="module-description">This interactive module is grounded in Harman Hanjra’s project system. Use this surface for architecture, evidence, implementation notes, and verified next actions.</p><a className="primary" href="https://github.com/harmanhanjra" target="_blank" rel="noreferrer">Inspect GitHub ↗</a></section></div>}
 </main>
}
